2024-01-30 10:50:49,868 ERROR: Exception on /user/fei [GET] [in D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\routes.py", line 85, in user
    return render_template('user.html',user=user,posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Coding\Python\flask\micoblog05\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Coding\Python\flask\micoblog05\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\templates\user.html", line 16, in block 'content'
    {% include '_post.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\templates\_post.html", line 5, in top-level template code
    <a href="{{ url.for('user',username=post.author.username) }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'url' is undefined
2024-01-30 10:50:53,430 ERROR: Exception on /user/fei [GET] [in D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\routes.py", line 85, in user
    return render_template('user.html',user=user,posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Coding\Python\flask\micoblog05\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Coding\Python\flask\micoblog05\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\templates\user.html", line 16, in block 'content'
    {% include '_post.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\templates\_post.html", line 5, in top-level template code
    <a href="{{ url.for('user',username=post.author.username) }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'url' is undefined
2024-01-30 10:50:57,410 ERROR: Exception on /user/fei [GET] [in D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\routes.py", line 85, in user
    return render_template('user.html',user=user,posts=posts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Coding\Python\flask\micoblog05\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Coding\Python\flask\micoblog05\app\templates\base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\templates\user.html", line 16, in block 'content'
    {% include '_post.html' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\app\templates\_post.html", line 5, in top-level template code
    <a href="{{ url.for('user',username=post.author.username) }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\flask\micoblog05\.venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'url' is undefined
2024-01-30 10:51:34,147 INFO: micoblog05 startup [in D:\Coding\Python\flask\micoblog05\app\__init__.py:46]
2024-01-30 10:53:45,099 INFO: micoblog05 startup [in D:\Coding\Python\flask\micoblog05\app\__init__.py:46]
2024-01-30 11:00:12,365 INFO: micoblog05 startup [in D:\Coding\Python\flask\micoblog05\app\__init__.py:46]
2024-01-30 11:00:39,833 INFO: micoblog05 startup [in D:\Coding\Python\flask\micoblog05\app\__init__.py:46]
2024-01-30 11:41:04,828 INFO: micoblog05 startup [in D:\Coding\Python\flask\micoblog05\app\__init__.py:48]
2024-01-31 09:40:44,897 INFO: micoblog05 startup [in D:\Coding\Python\flask\micoblog05\app\__init__.py:57]
2024-01-31 09:41:11,372 INFO: micoblog05 startup [in D:\Coding\Python\flask\micoblog05\app\__init__.py:57]
2024-01-31 09:43:27,366 INFO: micoblog05 startup [in D:\Coding\Python\flask\micoblog05\app\__init__.py:57]
